# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='likes_books_app.users'),
        ),
    ]
