# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books_app', '0002_auto_20180219_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='books',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='books',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='likes_books_app.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded', to='likes_books_app.User'),
        ),
    ]
